### ISSUE TITLE
pretrained models?

### ISSUE THREAD

**Issue by jiasenlu** [wassname/world-models-sonic-pytorch#1]
Hi @wassname 

Thanks for your code. I wonder where is the pretrained model? and how to run the code? 

Best

Jiasen

**Comment by wassname** [comment]
Follow the instructions in the readme, and if you run into any trouble ask here. No one except me has run it so the instructions are likely incomplete, so feel free to ask if you run into a problems. Then I can update the readme for the next person.

I noticed I forgot to add the notebooks, sorry, I've added them now.

Here's some of my pretrained weights: https://drive.google.com/drive/folders/1-Sq82fRwJy1oEdUunyyvKxPMZTal_k8J?usp=sharing

**Comment by jiasenlu** [comment]
Thanks!
